[tasks.install-llvm-tools]
install_crate = { rustup_component_name = "llvm-tools" }

[tasks.flip-link]
install_crate = { crate_name = "flip-link", binary = "flip-link", test_arg = ["-h"] }

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.objcopy-dongle]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "dongle",
    "--",
    "-O",
    "ihex",
    "lapka-36-dongle.hex",
]
dependencies = ["build"]

[tasks.objcopy-left]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "left",
    "--",
    "-O",
    "ihex",
    "lapka-36-left.hex",
]
dependencies = ["build"]

[tasks.objcopy-right]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "right",
    "--",
    "-O",
    "ihex",
    "lapka-36-right.hex",
]
dependencies = ["build"]

[tasks.bin-dongle]
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "dongle",
    "--",
    "-O",
    "binary",
    "lapka-36-dongle.bin",
]
dependencies = ["build"]

[tasks.bin-left]
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "left",
    "--",
    "-O",
    "binary",
    "lapka-36-left.bin",
]
dependencies = ["build"]

[tasks.bin-right]
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "right",
    "--",
    "-O",
    "binary",
    "lapka-36-right.bin",
]
dependencies = ["build"]

[tasks.bin]
dependencies = ["bin-dongle", "bin-left", "bin-right"]

[tasks.uf2-dongle]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
    "hex-to-uf2",
    "--help",
] }
command = "cargo"
args = [
    "hex-to-uf2",
    "--input-path",
    "lapka-36-dongle.hex",
    "--output-path",
    "lapka-36-dongle.uf2",
    "--family",
    "nrf52840",
]
dependencies = ["objcopy-dongle"]

[tasks.uf2-left]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
    "hex-to-uf2",
    "--help",
] }
command = "cargo"
args = [
    "hex-to-uf2",
    "--input-path",
    "lapka-36-left.hex",
    "--output-path",
    "lapka-36-left.uf2",
    "--family",
    "nrf52840",
]
dependencies = ["objcopy-left"]

[tasks.uf2-right]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
    "hex-to-uf2",
    "--help",
] }
command = "cargo"
args = [
    "hex-to-uf2",
    "--input-path",
    "lapka-36-right.hex",
    "--output-path",
    "lapka-36-right.uf2",
    "--family",
    "nrf52840",
]
dependencies = ["objcopy-right"]

[tasks.uf2]
dependencies = ["uf2-dongle", "uf2-left", "uf2-right"]
